WITH RECURSIVE time_list AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM time_list 
    WHERE HOUR < 23
)

SELECT T.HOUR AS HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM time_list T
LEFT OUTER JOIN ANIMAL_OUTS O ON T.HOUR = HOUR(O.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR