-- 코드를 입력하세요
SELECT
    B.TITLE,
    B.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B
-- 게시글과 댓글 테이블을 공통 분모인 BOARD_ID로 INNER JOIN
INNER JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
-- %Y-%m 형태로 DATE_FORMAT
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;